// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webshopAPI.domain.Entities;

public partial class Order
{
    public int Id { get; set; }

    public DateTime Timestamp { get; set; }

    public int UserId { get; set; }

    public string PaymentMethod { get; set; }

    public string ShipmentMethod { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<OrderItems> OrderItems { get; set; } = new List<OrderItems>();

    public virtual ICollection<Service> Service { get; set; } = new List<Service>();
}