// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webshopAPI.domain.Entities;

public partial class Product
{
    public int Id { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public int Price { get; set; }

    public int? Discount { get; set; }

    public int Quantity { get; set; }

    public int CategoryId { get; set; }

    public int VendorId { get; set; }

    public bool Trending { get; set; }

    public bool Active { get; set; }

    public string ImageUrl { get; set; }

    public bool OurChoice { get; set; }

    public virtual ICollection<Cart> Cart { get; set; } = new List<Cart>();

    public virtual ProductCategory Category { get; set; }

    public virtual ICollection<OrderItems> OrderItems { get; set; } = new List<OrderItems>();

    public virtual ICollection<Review> Review { get; set; } = new List<Review>();

    public virtual Vendor Vendor { get; set; }
}