// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webshopAPI.domain.Entities;

public partial class PromotionMail
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }
}