// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webshopAPI.domain.Entities;

public partial class Review
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int UserId { get; set; }

    public string ReviewText { get; set; }

    public int Star { get; set; }

    public virtual Product Product { get; set; }

    public virtual Users User { get; set; }
}