// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webshopAPI.domain.Entities;

public partial class Users
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Username { get; set; }

    public string PhoneNumber { get; set; }

    public string PostalNumber { get; set; }

    public string Address { get; set; }

    public bool Admin { get; set; }

    public bool Active { get; set; }

    public string AvatarUrl { get; set; }

    public byte[] PasswordHash { get; set; }

    public byte[] PasswordSalt { get; set; }

    public virtual ICollection<Cart> Cart { get; set; } = new List<Cart>();

    public virtual ICollection<Review> Review { get; set; } = new List<Review>();
}